// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8PJAHybpJup35zR51ISkobwlWBmbFfuI',
    appId: '1:575263779734:web:b3f216c9c204a104184bb7',
    messagingSenderId: '575263779734',
    projectId: 'aplikasi-jokka',
    authDomain: 'aplikasi-jokka.firebaseapp.com',
    storageBucket: 'aplikasi-jokka.firebasestorage.app',
    measurementId: 'G-K6NF1BPWWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkcke77XPN6gDJpquKZcN0MWoXRFX9yB8',
    appId: '1:575263779734:android:0bfc74cc8f607493184bb7',
    messagingSenderId: '575263779734',
    projectId: 'aplikasi-jokka',
    storageBucket: 'aplikasi-jokka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUk4AgvEu6xnEckqhQevDWLvaUuTmE1wY',
    appId: '1:575263779734:ios:9dc7eeb9214d5a56184bb7',
    messagingSenderId: '575263779734',
    projectId: 'aplikasi-jokka',
    storageBucket: 'aplikasi-jokka.firebasestorage.app',
    iosBundleId: 'com.example.jokkaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUk4AgvEu6xnEckqhQevDWLvaUuTmE1wY',
    appId: '1:575263779734:ios:9dc7eeb9214d5a56184bb7',
    messagingSenderId: '575263779734',
    projectId: 'aplikasi-jokka',
    storageBucket: 'aplikasi-jokka.firebasestorage.app',
    iosBundleId: 'com.example.jokkaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8PJAHybpJup35zR51ISkobwlWBmbFfuI',
    appId: '1:575263779734:web:c59a71bfa9fd460b184bb7',
    messagingSenderId: '575263779734',
    projectId: 'aplikasi-jokka',
    authDomain: 'aplikasi-jokka.firebaseapp.com',
    storageBucket: 'aplikasi-jokka.firebasestorage.app',
    measurementId: 'G-WMYJB3LPB9',
  );
}
